version: '3.8'
services:
  web:
    image: ${REGISTRY}/${IMAGE_NAME}:${VERSION}
    deploy:
      update_config:
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.http.routers.swagger-web.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.swagger-web.entrypoints=websecure
        - traefik.http.routers.swagger-web.tls=true
        - traefik.http.routers.swagger-web.tls.certresolver=myotherresolver
        - traefik.http.services.swagger-web-service.loadbalancer.server.port=80
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true

